name: presentation
version: 1.0.0+1
publish_to: 'none'


scripts:
  build: flutter pub get && dart run build_runner build -d
  generate: ' '
  clean: dart run build_runner clean && flutter clean

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=2.8.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  domain:
    path: '../domain'
  injectable:
  get_it:
  flutter_bloc: ^8.1.3
  go_router: ^8.0.5
  async: ^2.11.0
  sound_stream: ^0.4.1
  qr_flutter: ^4.1.0
  flutter_zxing: ^1.7.0
  rxdart: ^0.27.7
  settings_ui: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  injectable_generator:
  build_runner:

flutter:
  uses-material-design: true
  generate: true