name: domain
version: 1.0.0+1
publish_to: 'none'

scripts:
  build: flutter pub get && dart run build_runner build -d
  generate: " "
  clean: dart run build_runner clean && flutter clean

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  injectable:
  get_it:
  async: ^2.11.0

dev_dependencies:
  flutter_lints: ^3.0.0
  injectable_generator:
  build_runner:

flutter:
  uses-material-design: true